[tasks.bench]
workspace = false
command = "cargo"
args = ["bench", "--package", "benchmark_runner"]


[tasks.bench-clean-results]
workspace = false
command = "rm"
args = ["-r", "benchmark_runner/target/criterion"]


[tasks.readme]
workspace = false
command = "cargo"
args = ["readme", "--output", "README.md"]
